name: 错误报告
description: ' 创建一个错误报告以帮助我改进 '
title: "[BUG] <简短描述>"
labels: [bug]
body:
- type: textarea
  id: version
  attributes:
    label: 填写错误
    description: >-
      简单明了的描述一下错误.
    placeholder: '实例: xx配置不工作/有回弹/有严重误判'
  validations:
    required: true

- type: textarea
  attributes:
    label: 日志文件或 图像/视频
    description: |
      上传你日志文件里反作弊误判/回弹/绕过的消息提示. |
      你也可以上传误判/回弹/绕过的视频或图像.
      
      提示: 你可以通过单击此区域将其突出显示.然后将文件拖入或在工具栏上的🖼选项上来选择上传文件
  validations:
    required: true

- type: textarea
  attributes:
    label: 复现步骤
    description: 重现错误的步骤.
    placeholder: |
      1. 启动服务器和反作弊
      ... *(您重现错误的一组操作)*
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: 预期行为
    description: 对您期望发生的事情进行简单描述
    placeholder: '实例: 我希望服务器没有误判/回弹/绕过'
  validations:
    required: true

- type: textarea
  attributes:
    label: 平台
    description: |
      例子:
        - **服务器核心**: spigot/purpur/paper
        - **服务器类型**: 生存/小游戏/角色扮演（RPG）
        - **服务器版本**: 1.8.8/1.12.2/1.17/1.19
        - **反作弊配置版本**: [NoCheatPlus || version-1.0.0 ]
    value: |
        - 服务器核心: 
        - 服务器类型: 
        - 服务器版本: 
        - 反作弊配置版本: 
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: 其他补充?
    description: |
      在此处填写该问题的任何上下文，可以是更详细的描述.
  validations:
    required: false
